//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class civ_EmpAttendance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public civ_EmpAttendance()
        {
            this.civ_EmpAttendanceList = new HashSet<civ_EmpAttendanceList>();
        }
    
        public int Id { get; set; }
        public System.DateTime TimeIn { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public bool IsAvailable { get; set; }
        public Nullable<decimal> Bonus_hours { get; set; }
        public Nullable<decimal> Pelanty_hours { get; set; }
        public Nullable<decimal> Working_hours { get; set; }
        public byte[] Comments { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public int EmpIDFK { get; set; }
        public int CompanyIDFK { get; set; }
    
        public virtual civ_Company civ_Company { get; set; }
        public virtual civ_Employees civ_Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<civ_EmpAttendanceList> civ_EmpAttendanceList { get; set; }
    }
}
