//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class civ_Clinet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public civ_Clinet()
        {
            this.civ_ClinetContactPerson = new HashSet<civ_ClinetContactPerson>();
        }
    
        public int ClientID { get; set; }
        public string ClientName { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public bool IsActive { get; set; }
        public string NTN { get; set; }
        public int AddressIDFK { get; set; }
        public int CompanyIDFK { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreadtedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual civ_Address civ_Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<civ_ClinetContactPerson> civ_ClinetContactPerson { get; set; }
    }
}
