//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class civ_EmployeeTransfer
    {
        public int Id { get; set; }
        public int SiteIDFK { get; set; }
        public int ProjectIDFK { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int EmployeeIDFK { get; set; }
        public int CompanyIDFK { get; set; }
    
        public virtual civ_Company civ_Company { get; set; }
        public virtual civ_Project civ_Project { get; set; }
        public virtual civ_Sites civ_Sites { get; set; }
    }
}
