//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class civ_Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public civ_Project()
        {
            this.civ_EmployeeTransfer = new HashSet<civ_EmployeeTransfer>();
        }
    
        public int Id { get; set; }
        public string ProjectName { get; set; }
        public bool IsActive { get; set; }
        public int CompanyIDFK { get; set; }
        public int SiteIDFK { get; set; }
    
        public virtual civ_Company civ_Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<civ_EmployeeTransfer> civ_EmployeeTransfer { get; set; }
        public virtual civ_Sites civ_Sites { get; set; }
    }
}
