//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class civ_ClinetContactPerson
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public byte[] Email { get; set; }
        public string PhoneNo1 { get; set; }
        public string PhoneNo2 { get; set; }
        public string Comments { get; set; }
        public int ClientIDFK { get; set; }
    
        public virtual civ_Clinet civ_Clinet { get; set; }
    }
}
