//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class civ_DepDesgnation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public civ_DepDesgnation()
        {
            this.civ_Employees = new HashSet<civ_Employees>();
        }
    
        public int Id { get; set; }
        public string Desgnation { get; set; }
        public int DepartmentIDFK { get; set; }
        public bool IsActive { get; set; }
    
        public virtual civ_Department civ_Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<civ_Employees> civ_Employees { get; set; }
    }
}
