//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SinacoERPEntities : DbContext
    {
        public SinacoERPEntities()
            : base("name=SinacoERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<civ_Address> civ_Address { get; set; }
        public virtual DbSet<civ_Cities> civ_Cities { get; set; }
        public virtual DbSet<civ_Clinet> civ_Clinet { get; set; }
        public virtual DbSet<civ_ClinetContactPerson> civ_ClinetContactPerson { get; set; }
        public virtual DbSet<civ_Company> civ_Company { get; set; }
        public virtual DbSet<civ_CompanyType> civ_CompanyType { get; set; }
        public virtual DbSet<civ_Countries> civ_Countries { get; set; }
        public virtual DbSet<civ_Department> civ_Department { get; set; }
        public virtual DbSet<civ_DepDesgnation> civ_DepDesgnation { get; set; }
        public virtual DbSet<civ_EmpAttendance> civ_EmpAttendance { get; set; }
        public virtual DbSet<civ_EmpAttendanceList> civ_EmpAttendanceList { get; set; }
        public virtual DbSet<civ_Employees> civ_Employees { get; set; }
        public virtual DbSet<civ_EmployeeTransfer> civ_EmployeeTransfer { get; set; }
        public virtual DbSet<civ_EmployeeTypes> civ_EmployeeTypes { get; set; }
        public virtual DbSet<civ_EmpTypeDeptMap> civ_EmpTypeDeptMap { get; set; }
        public virtual DbSet<civ_Project> civ_Project { get; set; }
        public virtual DbSet<civ_Religon> civ_Religon { get; set; }
        public virtual DbSet<civ_Sites> civ_Sites { get; set; }
        public virtual DbSet<civ_States> civ_States { get; set; }
    }
}
